
package test.mdb.core.ws.client.stub.webgateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebGateway", targetNamespace = "http://impl.gateway.mdb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebGateway {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Open")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Open", targetNamespace = "http://impl.gateway.mdb/", className = "test.mdb.core.ws.client.stub.webgateway.Open")
    @ResponseWrapper(localName = "OpenResponse", targetNamespace = "http://impl.gateway.mdb/", className = "test.mdb.core.ws.client.stub.webgateway.OpenResponse")
    public String open(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testInvoke", targetNamespace = "http://impl.gateway.mdb/", className = "test.mdb.core.ws.client.stub.webgateway.TestInvoke")
    @ResponseWrapper(localName = "testInvokeResponse", targetNamespace = "http://impl.gateway.mdb/", className = "test.mdb.core.ws.client.stub.webgateway.TestInvokeResponse")
    public String testInvoke();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "main", targetNamespace = "http://impl.gateway.mdb/", className = "test.mdb.core.ws.client.stub.webgateway.Main")
    @ResponseWrapper(localName = "mainResponse", targetNamespace = "http://impl.gateway.mdb/", className = "test.mdb.core.ws.client.stub.webgateway.MainResponse")
    public byte[] main(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

}
